####################
# This script aims at ensuring the conformity of the R code with the one of
# Victor for the post-processing part.
#
# Descostes - July 2024 - R-4.4.1
####################

library("dplyr")
library("ggplot2")


##################
# PARAMETERS
##################

## Objects or files generated by Victor or documentation/explore.R
ecdfvicpath <- "/g/romebioinfo/Projects/tepr/downloads/Ecdf_victor.tsv"

## Objects or files generated with downstream.R
ecdfnicpath <- "/g/romebioinfo/tmp/downstream/dfmeandiff.rds"

outputfolder <- "/g/romebioinfo/tmp/downstream"


##################
# MAIN
##################

## Reading both ecdf
ecdfvic <- read.delim(ecdfvicpath, header = TRUE)
ecdfnic <- readRDS(ecdfnicpath)

## Plotting Fx for each replicate and condition
genenamevec <- c("M6PR", "ARF5", "EGFR", "HDDC2", "LINC01619")


invisible(sapply(genenamevec, function(currentgene, ecdfnic, ecdfvic) {

  ## Comparing Fx
  gFx <- ggplot() +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_HS1score), color="red", linetype=2) +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_HS2score), color="darkred", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_HS_rep1_score), color="red") +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_HS_rep2_score), color="darkred") +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_ctrl1score), color="blue", linetype=2) +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_ctrl2score), color="darkblue", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_ctrl_rep1_score), color="blue") +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_ctrl_rep2_score), color="darkblue") +
  ylim(0,1) + ylab("Fx") + theme_classic() + ggtitle(currentgene)

  ## Comparing mean values
  gmeanval <- ggplot() +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,mean_value_HS), color="red", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,mean_value_HS), color="red") +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,mean_value_ctrl), color="blue", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,mean_value_ctrl), color="blue") +
  ylab("mean_value") + theme_classic() + ggtitle(currentgene)

  ## Comparing mean Fx
  gmeanfx <- ggplot() +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,mean_Fx_HS), color="red", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,mean_Fx_HS), color="red") +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,mean_Fx_ctrl), color="blue", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,mean_Fx_ctrl), color="blue") +
  ylab("mean_fx") + theme_classic() + ggtitle(currentgene)

  ## Comparing diff values
  # gdiffval <- ggplot() +
  # geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Diff_meanvalue_HS_ctrl), color="red", linetype=2) +
  # geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Diff_meanvalue_HS_ctrl), color="red") +
  # geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Diff_meanvalue_ctrl_HS), color="blue", linetype=2) +
  # geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Diff_meanvalue_ctrl_HS), color="blue") +
  # ylab("diff_value") + theme_classic() + ggtitle(currentgene)

  ## Comparing diff Fx
  gdifffx <- ggplot() +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,diff_Fx_HS), color="red", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,diff_Fx_HS), color="red") +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,diff_Fx_ctrl), color="blue", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,diff_Fx_ctrl), color="blue") +
  ylab("diff_fx") + theme_classic() + ggtitle(currentgene)

  ggplot2::ggsave(filename = paste0(currentgene, "_Fx.png"), plot = gFx,
            device = "png", path = outputfolder)
  ggplot2::ggsave(filename = paste0(currentgene, "_meanvalue.png"),
    plot = gmeanval, device = "png", path = outputfolder)
  ggplot2::ggsave(filename = paste0(currentgene, "_meanfx.png"),
    plot = gmeanfx, device = "png", path = outputfolder)
  # ggplot2::ggsave(filename = paste0(currentgene, "_diffval.png"),
  #   plot = gdiffval, device = "png", path = outputfolder)
  ggplot2::ggsave(filename = paste0(currentgene, "_difffx.png"),
    plot = gdifffx, device = "png", path = outputfolder)

}, ecdfnic, ecdfvic))

