####################
# This script aims at ensuring the conformity of the R code with the one of
# Victor for the post-processing part.
#
# Descostes - July 2024 - R-4.4.1
####################

library("dplyr")
library("ggplot2")


##################
# PARAMETERS
##################

## Objects or files generated by Victor or documentation/explore.R
ecdfvicpath <- "/g/romebioinfo/Projects/tepr/downloads/Ecdf_victor.tsv"

## Objects or files generated with downstream.R
ecdfnicpath <- "/g/romebioinfo/tmp/downstream/resultsecdf.rds"

outputfolder <- "/g/romebioinfo/tmp/downstream"


##################
# MAIN
##################

## Reading both ecdf
ecdfvic <- read.delim(ecdfvicpath, header = TRUE)
ecdfnic <- readRDS(ecdfnicpath)

## Plotting Fx for each replicate and condition
genenamevec <- c("M6PR", "ARF5", "EGFR", "HDDC2", "LINC01619")

invisible(sapply(genenamevec, function(currentgene, testnic, testvic) {
  g <- ggplot() +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_HS1score), color="red", linetype=2) +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_HS2score), color="darkred", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_HS_rep1_score), color="red") +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_HS_rep2_score), color="darkred") +

  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_ctrl1score), color="blue", linetype=2) +
  geom_line(data=ecdfnic %>% filter(gene==currentgene), aes(coord,Fx_ctrl2score), color="darkblue", linetype=2) +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_ctrl_rep1_score), color="blue") +
  geom_line(data=ecdfvic %>% filter(gene==currentgene), aes(coord,Fx_ctrl_rep2_score), color="darkblue") +

  ylim(0,1) + ylab("Fx") + theme_classic() + ggtitle(currentgene)

  ggplot2::ggsave(filename = paste0(currentgene, "_Fx.png"), plot = g,
            device = "png", path = outputfolder)

}, testnic, testvic))
